name: augment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab=3.3
  - matplotlib=3.4
  - pandas=1.3
  - jupyter_nbextensions_configurator=0.4.1
  - pip:
    - albumentations==1.0
    - ipywidgets==7.7
    - nlpaug==1.1.7
    - nltk==3.6.2
    - RISE==5.7.1
    - sentencepiece==0.1.96
    - torch==1.9.0
    - transformers==4.10.2